### ISSUE TITLE
GPU、MSCOCO、CIDER

### ISSUE THREAD

**Issue by qqq-gif** [jchenghu/ExpansionNet_v2#13] opened 2024-07-24 09:35 UTC
Dear Sir:
I am reproducing your work and now I have three questions I would like to get your help:
1. this is a screenshot of the performance of my device, is it possible to perform four stages of training on one 3090? This is a screenshot of my GPU usage.
![gpu](https://github.com/user-attachments/assets/cd821329-1f56-4fcc-ad03-02c2ce992571)
![GPU2](https://github.com/user-attachments/assets/f328473d-06d3-4ebf-be2b-76c6f06e35d4)
2. in the link you provided to download the MSCOCO2014 dataset, the size of the train2014 zip package is about 10GB, and I am using the train2014 that I downloaded before, which is about 1GB, and the number of images is the same, but I don't know why the size difference is so big, may I ask how it affects the results?
![train2014](https://github.com/user-attachments/assets/86ed0985-880e-4d90-82a7-63d1640a86fb)
3. I used the rf_model_140.4-002.pth you provided for verification, why is my cider only 135, here is the command I executed and the screenshot:
![cider](https://github.com/user-attachments/assets/c81da9bf-a2f2-4ccd-8fce-e9f27aeff549)

 python /root/ExpansionNet_v2-master/ExpansionNet_v2-master/test.py --N_enc 3 --N_dec 3 --model_dim 512 --num_gpus 1 --eval_beam_sizes [5] --is _end_to_end True --eval
_parallel_batch_size 4 --images_path /root/ExpansionNet_v2-master/ExpansionNet_v2-master/image/ ---save_model_path /root/ExpansionNet_v2 -master/ExpansionNet_v2-master/github_ignore_material/saves/rf_model_140.4-002.pth

**Comment by jchenghu** [comment] 2024-07-24 09:46
Hi,

- About the question 1):
 Yes your machine is more than enough to train all four stages (considering that it can be trained on a 3070 with 8GB), if you get out of memory errors, tune  `--batch_size` , `--num_accum` (number of gradient accumulations) and `--eval_batch_size` across the four stages  (for instance if the end-to-end does not fit your memory, try halving the batch size and doubling the number of accumulations).

- About questions 2 and 3):
the COCO2014 zip should weigh about 10 GB. Maybe your current version consists of smaller images?
In that case, the model resizes all images into 384x384, but since your images were initially smaller, some details are lost during the transition, which might also explain the lower CIDEr score
(assuming you tested on your 1GB coco dataset)

**Comment by qqq-gif** [comment] 2024-07-24 10:30
Dear Sir:
Thank you for replying so quickly, based on your reply below I will try the training, good luck!

**Comment by jchenghu** [comment] 2024-07-24 10:46
Your welcome!

I just noticed a small detail, I noticed now, that the checkpoint name is "rf_model_140.4-002.pth" instead of "rf_model_140.4.pth" Are you sure you sure the complete file was downloaded? (check that the size is 2.6GB)  because
from the name it looks like it is only a portion of the whole checkpoint

**Comment by qqq-gif** [comment] 2024-07-24 10:56
Dear Sir:
I have verified that my checkpoint file name is rf_model_140.4-002.pth not rf_model_140.4 and also the size is about 2.6GB.
![2 6](https://github.com/user-attachments/assets/00b16a20-d559-451d-a5c6-a7fb830f54dd)

I am in the middle of the first phase of training but my terminal is not responding.Is it stuck or is it in training. Can you please see if my output is correct?
![train](https://github.com/user-attachments/assets/80010c10-bfec-49f9-a89d-e505ce91b5f2)

**Comment by jchenghu** [comment] 2024-07-24 11:08
I believe the name should be 'rf_model_140.4.pth' not 'rf_model_140.4-002.pth'. maybe check the md5sum checksum, it should be: e0c006c318ca9baf5e4470ca89f0bdc0
I wonder if this caused the previous error


Regarding the image, yes it should be training normally, you should see in 'nvidia-smi' that the GPU is working

**Comment by qqq-gif** [comment] 2024-07-24 12:11
Dear Sir:
Sorry, I thought the name of the checkpoint you posted was rf_model_140.4-002.pth, now I re-downloaded rf_model_140.4 and then the training is also running normally, thanks again for your busy reply!

**Comment by qqq-gif** [comment] 2024-07-26 05:26
Dear Sir.
    When I do the third step of training (Cross-Entropy Training: End to End Training), I encounter the following error: torch.cuda.OutOfMemoryError: CUDA out of memory. tried to allocate 108.00 MiB ( GPU 0; 23.69 GiB total capacity; 21.52 GiB already allocated; 68.81 MiB free; 23.16 GiB reserved in total by PyTorch) If reserved memory is >> allocated If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation. See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF, 
![train2](https://github.com/user-attachments/assets/aa029d69-eee7-4657-848a-199c274bb58b)

    but my training progress has reached 95%. , I want to know why the out of memory problem occurs when I end the training right away, what should I do to fix the error (my train batch_size has been reduced from 16 to 8 at the beginning of the training, train batch_size: 8), and can I modify the error to continue training on this basis, here is the command I used:

python /root/ExpansionNet_v2-master/ExpansionNet_v2-master/train.py --N_enc 3 --N_dec 3 --model_dim 512 --optim_type radam --seed 775533   --sched_type custom_warmup_anneal --warmup 1 --lr 3e-5 --anneal_coeff 0.55 --anneal_every_epoch 1 --enc_drop 0.3 --dec_drop 0.3 --enc_input_drop 0.3 --dec_input_drop 0.3 --drop_other 0.3 --batch_size 8 --num_accum 3 --num_gpus 1 --ddp_sync_port 11317 --eval_beam_sizes [3] --save_path /root/ExpansionNet_v2-master/ExpansionNet_v2-master/github_ignore_material/saves/ --save_every_minutes 60 --how_many_checkpoints 1 --is_end_to_end True --images_path /root/ExpansionNet_v2-master/ExpansionNet_v2-master/image/ --partial_load True --backbone_save_path/root/ExpansionNet_v2-master/ExpansionNet_v2 master/github_ignore_material/raw_data/swin_large_patch4_window12_384_22k.pth --body_save_path /root/ExpansionNet_v2-master/ExpansionNet_v2-master/github_ignore_material/saves/checkpoint_2024-07-24-23:18:45_epoch7it11807bs48_xe_.pth --print_every_iter 15000 --eval_every_iter 999999 --reinforce False --num_epochs 2

**Comment by jchenghu** [comment] 2024-07-26 08:19
Hi, it might be caused by the evaluation batch size, 

try setting `--eval_parallel_batch_size` to a much lower value, like 1, 2, 4, 8.... by default is 16,

Final command should be


python /root/ExpansionNet_v2-master/ExpansionNet_v2-master/train.py --N_enc 3 --N_dec 3 --model_dim 512 --optim_type radam --seed 775533 --sched_type custom_warmup_anneal --warmup 1 --lr 3e-5 --anneal_coeff 0.55 --anneal_every_epoch 1 --enc_drop 0.3 --dec_drop 0.3 --enc_input_drop 0.3 --dec_input_drop 0.3 --drop_other 0.3 --batch_size 8 --num_accum 3 --num_gpus 1 --ddp_sync_port 11317 --eval_beam_sizes [3] --save_path /root/ExpansionNet_v2-master/ExpansionNet_v2-master/github_ignore_material/saves/ --save_every_minutes 60 --how_many_checkpoints 1 --is_end_to_end True --images_path /root/ExpansionNet_v2-master/ExpansionNet_v2-master/image/ --partial_load True --backbone_save_path/root/ExpansionNet_v2-master/ExpansionNet_v2 master/github_ignore_material/raw_data/swin_large_patch4_window12_384_22k.pth --body_save_path /root/ExpansionNet_v2-master/ExpansionNet_v2-master/github_ignore_material/saves/checkpoint_2024-07-24-23:18:45_epoch7it11807bs48_xe_.pth --print_every_iter 15000 --eval_every_iter 999999 --reinforce False --num_epochs 2  --eval_parallel_batch_size 2
 ______________________________________^^^^^^^^^^ added this part

If this caused the Out of Memory error, I should change the default value since it is a common issue, please let me know if the problem persists.

In any case, if changing eval_parallel_batch_size does solve your problem, you can effortlessly continue the previous training by simply re-executing the command, it should automatically load the previous checkpoint file

**Comment by qqq-gif** [comment] 2024-07-28 14:11
Dear Sir.
  I ran the command you replied , added --eval_parallel_batch_size 2, modified --body_save_path /root/ExpansionNet_v2-master/ExpansionNet_v2-master/github_ignore_ material/saves/checkpoint_2024-07-26-08:37:47_epoch1it66427bs8_xe_.pth (/root/ExpansionNet_v2-master/ExpansionNet_v2-master/github_ ignore_material/saves/checkpoint_2024-07-26-08:37:47_epoch1it66427bs8_xe_.pth is the last checkpoint of the third phase of training (Cross-Entropy Training: End to End Training) last checkpoint file), modified --save_every_minutes 10, however, the name of the newly generated checkpoint is checkpoint_2024-07-28-21:54:12_epoch0it1237bs8_xe_.pth, how do I determine if this is the same checkpoint that was generated in the last newly generated on top of the last one? And my previous checkpoint_2024-07-26-08:37:47_epoch1it66427bs8_xe_.pth has been replaced, how do I know how much longer to run it, do I have to run two more epochs? I would also like to know which phase weights are in the xe_model-004.pth you uploaded? Thanks for your reply!


![train3](https://github.com/user-attachments/assets/35088a7f-ed3b-4efc-b74d-6b4a8af5a445)

**Comment by jchenghu** [comment] 2024-07-29 03:04
Hi, the xe_checkpoint provided in the drive refers to the model at the end of the training Step 3 in the readme.

Regarding the first question, for better readability, I will simply refer to the complete path with the checkpoint name..

- So, the first training generated this checkpoint -> `checkpoint_2024-07-26-08:37:47_epoch1it66427bs8_xe_.pth`
but then it got interrupted by the memory error (I will set the default value of `eval_parallel_batch` to a smaller value, sorry for the inconvenience)
- I should have told you that when you resume the training, within the same training step, you should not use the `--backbone_save_path` and `--body_save_path` again like in the first execution, since these determine whether the model should resume training or perform a new one from scratch. When you specify these two arguments, the model training starts again from these partial checkpoints, instead of the one already present in `./github_ignore_material/saves/`.

This command creates ambiguity, since it is not clear, whether the model should look in the `save_path` for existing checkpoint or load from `backbone_save_path` and `body_save_path`. I decided to solve this conflict by giving priority to the latter two arguments.
 ` ` `
python train.py --N_enc 3 --N_dec 3  \
    --model_dim 512 --optim_type radam --seed 775533   --sched_type custom_warmup_anneal  \
    --warmup 1 --lr 3e-5 --anneal_coeff 0.55 --anneal_every_epoch 1 --enc_drop 0.3 \
    --dec_drop 0.3 --enc_input_drop 0.3 --dec_input_drop 0.3 --drop_other 0.3  \
    --batch_size 16 --num_accum 3 --num_gpus 1 --ddp_sync_port 11317 --eval_beam_sizes [3]  \
    --save_path ./github_ignore_material/saves/ --save_every_minutes 60 --how_many_checkpoints 1  \
    --is_end_to_end True --images_path ./github_ignore_material/raw_data/MS_COCO_2014/ --partial_load True \
    --backbone_save_path ./github_ignore_material/raw_data/swin_large_patch4_window12_384_22k.pth \
    --body_save_path ./github_ignore_material/saves/phase2_checkpoint \
    --print_every_iter 15000 --eval_every_iter 999999 \
    --reinforce False --num_epochs 2 &> output_file.txt &
 ` ` `
 
 To resume training, the command should look like this
  ` ` `
python train.py --N_enc 3 --N_dec 3  \
    --model_dim 512 --optim_type radam --seed 775533   --sched_type custom_warmup_anneal  \
    --warmup 1 --lr 3e-5 --anneal_coeff 0.55 --anneal_every_epoch 1 --enc_drop 0.3 \
    --dec_drop 0.3 --enc_input_drop 0.3 --dec_input_drop 0.3 --drop_other 0.3  \
    --batch_size 16 --num_accum 3 --num_gpus 1 --ddp_sync_port 11317 --eval_beam_sizes [3]  \
    --save_path ./github_ignore_material/saves/ --save_every_minutes 60 --how_many_checkpoints 1  \
    --is_end_to_end True --images_path ./github_ignore_material/raw_data/MS_COCO_2014/ --partial_load True \
    --print_every_iter 15000 --eval_every_iter 999999 \
    --reinforce False --num_epochs 2 &> output_file.txt &
  ` ` `
 (I simply removed the two arguments)
 
 So in your case, the model did not look in the  `save_path` folder for existing checkpoints and created a new one (` checkpoint_2024-07-28-21:54:12_epoch0it1237bs8_xe_.pth` ), which then replaced the previous one because it automatically keeps at most three checkpoints and discards the oldest ones.
 
 - Additionally, I just realized that you did not rename your checkpoints at the end of each training stage as instructed in the readme, for instance here 
 `--body_save_path /root/ExpansionNet_v2-master/ExpansionNet_v2-master/github_ignore_material/saves/checkpoint_2024-07-24-23:18:45_epoch7it11807bs48_xe_.pth`
you should rename the file into something like `my_step_2_checkpoint`, or simply avoid using `checkpoint` as the prefix, otherwise it can be overwritten like in the case of  `checkpoint_2024-07-26-08:37:47_epoch1it66427bs8_xe_.pth`.

So to answer your final question, I'm afraid you need to run two epochs again in the third step if you want to follow precisely the readme training :-(

Hope it helps

**Comment by qqq-gif** [comment] 2024-08-28 08:06
Dear Sir，
   Can you please tell me how to use this model to test it on my own dataset?

**Comment by jchenghu** [comment] 2024-08-28 13:10
Hi, 

If you haven't already, please check this [issue](https://github.com/jchenghu/ExpansionNet_v2/issues/5),
this should address both the training and testing datasets.

This [one](https://github.com/jchenghu/ExpansionNet_v2/issues/12) might be useful too.

Feel free to notify me in case those threads are not exhaustive enough :-)

**Comment by qqq-gif** [comment] 2024-08-31 03:45
Dear Sir，
I would like to know how you encode the position of the input sequence.
Would this be a good direction for improvement?

**Comment by jchenghu** [comment] 2024-09-01 02:45
Hi, 
 
The position of the input sequence is currently encoded by simple embedding vectors which one-hot is associated with the token position. This is not the standard practice (the positional encoder of the Transformer) but the result is pretty much the same. In this regard, changing the positional encoding (e.g. from embedding to the popular Transformer xPos) does not make much difference in this case so it might not be a very promising direction for improvements, but I could be wrong...

I hope I correctly understood your question, please let me know if you meant something else

**Comment by qqq-gif** [comment] 2024-09-01 06:22
Dear Sir，
  Thank you for your reply, is it possible for me to improve swintransformer then, or do you have any suggestions, thank you very much for your guidance!

**Comment by jchenghu** [comment] 2024-09-02 12:30
Hi, 

From a research perspective, I'm confident both the swin_transformer and the expansion_net fusion model can be improved, however, it depends on the resources, the type of improvement you want to make, and the topic you're interested in. 

For instance, performing research on the swin_transformer architecture is a much more computationally expensive task than the fusion model, since you would need to train also on ImageNet, for instance, in [this](https://arxiv.org/abs/2408.13963) work, we tried to improve the efficiency of the swin_transformer. However training difficulties resulted in a significant loss of score, and the release of our best model will be delayed a lot because training on ImageNet-22k is no trivial matter.

Regarding the fusion model, in my biased opinion, I think expansion_net has a lot of potential and interesting features compared to existing architectures (for instance [here](https://arxiv.org/abs/2408.13959)) but it focuses more on sequences, and we're currently working on finding more effective formulations of the expansion_net idea.


Although I'm biased toward expansion_net If you're a researcher in the early stages of your career, I would say, focus on the swin_transformer (if you have the resources) or improvements for image captioning that apply to any kind of model (not only expansion_net) because they are a much more popular topic. 

Either way, I'm thankful for your interest, and regardless of your decision, I hope this repository helps you in your research.

**Comment by jchenghu** [comment] 2024-09-06 15:18
Hi,

I'm closing the thread since I believe the original issue was solved, feel free to open a new one if needed (or re-open this one if related)

**Closed as completed by jchenghu** 2024-09-06 15:18 UTC
